### ISSUE TITLE
朋友就改了配置中的id，报错。

### ISSUE THREAD

**Issue by bilibiliSilentH** [Just-Prog/Bilibili_show_ticket_auto_order#11]
![3](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/assets/167333048/549fcffe-30ee-4492-a50d-d7b5d342f884)
朋友就改了配置中的id。

**Comment by Just-Prog** [comment]
`user_data.json` 里面有这个UID条目吗

**Comment by bilibiliSilentH** [comment]
没有。

**Comment by Just-Prog** [comment]
> 没有。

重新登录之后再试

**Comment by bilibiliSilentH** [comment]
好的感谢。
