### ISSUE TITLE
后续会增加票务库存查询功能吗

### ISSUE THREAD

**Issue by LFishThighL** [Just-Prog/Bilibili_show_ticket_auto_order#12]
有时候未开票的时候看到设置库存可以考虑选不同的票种，感觉不错

**Comment by Just-Prog** [comment]
c95dbe8

**Comment by Just-Prog** [comment]
> > [c95dbe8](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/commit/c95dbe87729c437d4750883069ba360ba6d62c68)
> 
> 这个新增的login.exe打开后显示的登录码用bilibili没法扫。。。可能是我的操作出错了，请问应该如何打开测试新功能？

系统版本是多少，出来的二维码是怎么显示的，方便的话遮掉中间区域截个图

**Comment by Just-Prog** [comment]
> > [c95dbe8](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/commit/c95dbe87729c437d4750883069ba360ba6d62c68)
> 
> 这个新增的login.exe打开后显示的登录码用bilibili没法扫。。。可能是我的操作出错了，请问应该如何打开测试新功能？

或者你把默认终端应用改成 “Windows 终端” / "Windows Terminal"再试一下，conhost的二维码容易直接裂掉
