### ISSUE TITLE
系统没装Edge / 登录卡住的解决方案 (beta)

### ISSUE THREAD

**Issue by Just-Prog** [Just-Prog/Bilibili_show_ticket_auto_order#15]
重写了一个登录器

覆盖掉软件包的`登录.exe`即可

[login.exe](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/releases/download/v1.9.1_dev/login.exe)

提示一下：Win7应该显示不出来完整二维码，Win10/11需要在Windows终端打开才能正常展示（自己换过字体当我没说）

**Comment by Cap-DoubleZhang** [comment]
用了刚更新的也打不开二维码，用图片扫描也登录不了
