### ISSUE TITLE
Bug: 登陆扫码 二维码在 cmd 部分中文字体环境下渲染异常

### ISSUE THREAD

**Issue by kumoSleeping** [Just-Prog/Bilibili_show_ticket_auto_order#16]
<img width="450" alt="image" src="https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/assets/124721166/f73ae5be-2f46-4730-864f-2d7eee21258c">

## 解决方法：cmd->属性->更换字体

系统环境: Windows Server 2022

感觉是很常见的问题，不过即使是这样我个人也推荐做一些说明或储存二维码图片到项目目录提供另一种解决方式

**Comment by Just-Prog** [comment]
fa3a99a
