### ISSUE TITLE
**请不要在哔哩哔哩宣传本项目**

### ISSUE THREAD

**Issue by Just-Prog** [Just-Prog/Bilibili_show_ticket_auto_order#17]
谢谢配合，开发团队还不想年纪轻轻就去和哔哩哔哩的法务团队喝茶

还请多点下举报:

https://www.bilibili.com/opus/942820947311722517

**Comment by Just-Prog** [comment]
基于友商项目 biliticket/BHYG 近期的反应，本项目可能会处于自保考虑在超大规模扩散/被哔哩哔哩官方拉闸发生时archive repo，届时将完全不再维护，谢谢配合

本项目也存在被哔哩哔哩直接takedown的可能性，维护者暂时还不想蹲局子……

也请在哔哩哔哩宣传/QQ微信拉群讨论本项目相关的用户删除相关内容以及解散群组，不再继续传播，谢谢合作。

**Comment by Just-Prog** [comment]
https://www.xiaohongshu.com/explore/667e3a31000000001e011808

走过路过点个举报谢谢喵

**Comment by linnene** [comment]
那些在QQ群里分享的人真以为自己是什么网络大神了，笑死人了。建议一人一码使用

**Comment by Just-Prog** [comment]
> 那些在QQ群里分享的人真以为自己是什么网络大神了，笑死人了。建议一人一码使用

没有条件搞这种，也不太合适

**Comment by 52aiyouxijiang** [comment]
支持
