### ISSUE TITLE
bug:二维码图片无法正常显示

### ISSUE THREAD

**Issue by LingChen-tsjmdlc** [Just-Prog/Bilibili_show_ticket_auto_order#18]
![image](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/assets/131531632/b27a415d-c6a7-4d00-a056-82474fe796c9)

## 操作环境
Windows 10 专业版 22H2
## 尝试过的方法【但均无法解决问题】
- 更换字体，但是没有显示正常的字体
![image](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/assets/131531632/bf0bc2d2-e7fb-4a0e-8a99-695ba4ab4ee5)
![image](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/assets/131531632/dd18af23-201a-4faf-808a-342cc6a94af8)
- 尝试强行更换字体，（[使用此链接方法](https://blog.csdn.net/Z_YMing/article/details/103082807)

**Comment by Just-Prog** [comment]
请使用Windows Terminal (Windows终端)打开，默认的 `conhost.exe` 对unicode字符支持有限，或者静待登录器与主脚本更新

**Comment by Just-Prog** [comment]
fa3a99a
