### ISSUE TITLE
抱歉哈，最近给您添麻烦了。

### ISSUE THREAD

**Issue by bilibiliSilentH** [Just-Prog/Bilibili_show_ticket_auto_order#19]
您说吧，不能传播的话我就把群解散了。

**Comment by Just-Prog** [comment]
> 您说吧，不能传播的话我就把群解散了。

保险起见最好解散，并确认“BW2024用不了脚本”，大规模传播很容易产生负面影响，一旦被哔哩哔哩法务部门和后端开发部门察觉问题很有可能会报废掉大部分脚本。
