### ISSUE TITLE
v1.10.1可以挂着抢余票吗？

### ISSUE THREAD

**Issue by mcliudian** [Just-Prog/Bilibili_show_ticket_auto_order#20]
新版本测试抢余票时发现只弹出了一次抢票，显示库存不足，然后就不动了，而旧版本会一直重复尝试抢票

**Comment by TurambarVAN** [comment]
抢BW24的时候提前试了一下，也是这样，但刚刚又试了一下变成了未开票，正在等待，希望他开票时会正常运行

**Comment by TurambarVAN** [comment]
而且bw24目前还只让手机端抢，估计是寄了

**Comment by mcliudian** [comment]
> 而且bw24目前还只让手机端抢，估计是寄了

我用程序抢到了，虽然锁网页但是程序依然可以用

**Comment by Emiyaplaymaker** [comment]
您好,请问我下载文件包的时候里面没有.exe的文件,我应该如何操作呢?使用VS code跑的时候显示no module named qrcode,求解答

**Comment by HARUKI66** [comment]
> > 而且bw24目前还只让手机端抢，估计是寄了
> 
> 我用程序抢到了，虽然锁网页但是程序依然可以用

请问还是开票前挂着就行是么

**Comment by mcliudian** [comment]
> 您好，请问我下载文件包的时候里面没有.exe的文件，我应该如何操作呢？使用VS code跑的时候显示no module named qrcode，求解答

不可能没有，你可能下错了

**Comment by HARUKI66** [comment]
> 您好,请问我下载文件包的时候里面没有.exe的文件,我应该如何操作呢?使用VS code跑的时候显示no module named qrcode,求解答

应该是下载[ticket_auto_order_x64_v1.10.1_PG.zip]，里面有exe的

**Comment by Emiyaplaymaker** [comment]
> > 您好，请问我下载文件包的时候里面没有.exe的文件，我应该如何操作呢？使用VS code跑的时候显示no module named qrcode，求解答
> 
> 不可能没有，你可能下错了

那些文件的后缀是.py,然后我downloadzip的,解压以后这些文件后缀还是.py

**Comment by Emiyaplaymaker** [comment]
> > 您好,请问我下载文件包的时候里面没有.exe的文件,我应该如何操作呢?使用VS code跑的时候显示no module named qrcode,求解答
> 
> 应该是下载[ticket_auto_order_x64_v1.10.1_PG.zip]，里面有exe的

请问在哪里下载

**Comment by HARUKI66** [comment]
> > > 您好,请问我下载文件包的时候里面没有.exe的文件,我应该如何操作呢?使用VS code跑的时候显示no module named qrcode,求解答
> > 
> > 
> > 应该是下载[ticket_auto_order_x64_v1.10.1_PG.zip]，里面有exe的
> 
> 请问在哪里下载

右边栏 releases

**Comment by Emiyaplaymaker** [comment]
> > > > 您好,请问我下载文件包的时候里面没有.exe的文件,我应该如何操作呢?使用VS code跑的时候显示no module named qrcode,求解答
> > > 
> > > 
> > > 应该是下载[ticket_auto_order_x64_v1.10.1_PG.zip]，里面有exe的
> > 
> > 
> > 请问在哪里下载
> 
> 右边栏 releases

好的,谢谢

**Comment by morgon0202** [comment]
> > 此外bw24目前还只让手机端抢，估计是寄了
> 
> 我用程序抢到了，虽然锁网页但是程序依然可以用

兄弟，你会闪退吗，我其他展子正常用bw老闪退

**Comment by zjzjzj9999** [comment]
新版本抢余票时发现只弹出了一次抢票，显示库存不足，然后就不动了，而旧版本会一直重复尝试抢票

**Comment by mcliudian** [comment]
> > > 此外bw24目前还只让手机端抢，估计是寄了
> > 
> > 
> > 我用程序抢到了，虽然锁网页但是程序依然可以用
> 
> 兄弟，你会闪退吗，我其他展子正常用bw老闪退

不清楚，好像也会

**Comment by mcliudian** [comment]
> 新版本抢余票时发现只弹出了一次抢票，显示库存不足，然后就不动了，而旧版本会一直重复尝试抢票

对，所以我想问能不能用来抢余票的

**Comment by FangRuiqi** [comment]
新版本抢余票时我也是这种情况，只弹出了一次抢票，显示库存不足，然后就不动了，而旧版本会一直重复尝试抢票

**Comment by Emiyaplaymaker** [comment]
我也是只弹出一次

**Comment by mcliudian** [comment]
> > > 此外bw24目前还只让手机端抢，估计是寄了
> > 
> > 
> > 我用程序抢到了，虽然锁网页但是程序依然可以用
> 
> 兄弟，你会闪退吗，我其他展子正常用bw老闪退

我也出现闪退的情况了，不知道咋搞

**Comment by zjutcaicai** [comment]
同问能否抢回流票

**Comment by Just-Prog** [comment]
> 您好,请问我下载文件包的时候里面没有.exe的文件,我应该如何操作呢?使用VS code跑的时候显示no module named qrcode,求解答

如果想要 exe 的话请从 releases 下载，直接下载zip只能下载源码
