### ISSUE TITLE
2024bw相关

### ISSUE THREAD

**Issue by morgon0202** [Just-Prog/Bilibili_show_ticket_auto_order#21]
使用其他展子可以正常下单，但是今年bw前面流程一样，尝试抢票之后运行一段时间会闪退（推测快抢到票了）没抢到会一直循环不会闪退，然后闪退后查看订单也未发现订单

**Comment by Emiyaplaymaker** [comment]
> 使用其他展子可以正常下单，但是今年bw前面流程一样，尝试抢票之后运行一段时间会闪退（推测快抢到票了）没抢到会一直循环不会闪退，然后闪退后查看订单也未发现订单

请问你用的链接是电脑端链接还是手机端链接

**Comment by 542864246** [comment]
> > 使用其他展子可以正常下单，但是今年bw前面流程一样，尝试抢票之后运行一段时间会闪退（推测快抢到票了）没抢到会一直循环不会闪退，然后闪退后查看订单也未发现订单
> 
> 请问你用的链接是电脑端链接还是手机端链接

>我用的事手机端的链接，也是跟这位同志一样的问题

**Comment by zjzjzj9999** [comment]
我用电脑端链接 和手机端链接都不会循环 应该用哪个链接  怎么才能循环

**Comment by 542864246** [comment]
俺也不清楚

**Comment by Emiyaplaymaker** [comment]
> > > 使用其他展子可以正常下单，但是今年bw前面流程一样，尝试抢票之后运行一段时间会闪退（推测快抢到票了）没抢到会一直循环不会闪退，然后闪退后查看订单也未发现订单
> > 
> > 
> > 请问你用的链接是电脑端链接还是手机端链接
> 
> > 我用的事手机端的链接，也是跟这位同志一样的问题

我刚才两个都试了,都不行

**Comment by Congregalis** [comment]
触发风控了
