### ISSUE TITLE
会闪退

### ISSUE THREAD

**Issue by shiyue-lgtm** [Just-Prog/Bilibili_show_ticket_auto_order#24]
1.9.1之后的版本都会闪退，而且是很快就秒退。图是正好截屏截到的
![图片1](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/assets/174189303/c0129209-dc44-494e-988e-e8d5ed6e7cb4)

**Comment by Just-Prog** [comment]
本地暂时无法复现，抱歉

**Comment by shiyue-lgtm** [comment]
好吧，作者辛苦了，我之前的1.9.1还可以用

**Comment by Just-Prog** [comment]
> 1.9.1之后的版本都会闪退，而且是很快就秒退。图是正好截屏截到的 ![图片1](https://private-user-images.githubusercontent.com/174189303/344392901-c0129209-dc44-494e-988e-e8d5ed6e7cb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTMxNzYsIm5iZiI6MTcyMDAxMjg3NiwicGF0aCI6Ii8xNzQxODkzMDMvMzQ0MzkyOTAxLWMwMTI5MjA5LWRjNDQtNDk0ZS05ODhlLWU4ZDVlZDZlN2NiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzIxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmVjNzU2ODY1ZmY0YmQwNzE0MDE3MzcwZTYyMGMxYWM1Y2E3MjIxM2M3MzhmZDlmNWU5NDU1MzUwNmU2ZWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5NcC9d2sIREIx_i_J5rw7xrtMbiCAuFLfETdFgnDCo0)

据上游 biliticket_gt 描述，其采用的验证码运行时在某些系统上有兼容性问题，建议排查一下系统版本是否过低

**Comment by shiyue-lgtm** [comment]
那应该是版本太低了，19年的windows
