### ISSUE TITLE
1.10.1开票后三秒闪退

### ISSUE THREAD

**Issue by Louveid** [Just-Prog/Bilibili_show_ticket_auto_order#27]
为了拉高中奖率所以一台机器分两个B号开的10.1，第三个B号同号双开10.2一起抢两天的，都是提前挂的等待开票，10.1的两个程序在开票后识别到开票大概两三秒就同时闪退（抱歉没看清最后闪退语句），10.2的双开倒是正常成功抢到了，所以发个issue问一下同设备是否支持多开不同账号抢票，还是说因为其他bug导致的闪退？10.2版本是初始版本没有使用patch1的替换exe.
麻烦了

**Comment by Just-Prog** [comment]
有可能是自动过验证码没成功

**Comment by Louveid** [comment]
好的麻烦了
