### ISSUE TITLE
文字验证过不去报错缺少参数 data

### ISSUE THREAD

**Issue by azunyamazing** [Just-Prog/Bilibili_show_ticket_auto_order#32]

**Comment by Louveid** [comment]
确实，补充截图
![Uploading QQ图片20240706121438.png…]()

**Comment by Louveid** [comment]
确实，补充截图
![Uploading QQ图片20240706121438.png…]()

**Comment by Louveid** [comment]
Geetest自动化检测出错。错误代码：bili ticket极验模块错误 {错误类型：Other("验证码自查出现错误”)
Geetest自动化检测出错。错误代码：bili ticket极验模块错误{错误类型：MissingParam(“data”
