### ISSUE TITLE
Many thanks!

### ISSUE THREAD

**Issue by squareRoot3** [Just-Prog/Bilibili_show_ticket_auto_order#37]
靠本项目帮我和朋友抢了 BW/BML, 真的太感谢了, 好人一生平安^ ^

**Comment by Just-Prog** [comment]
恭喜

~~顺便一提我自己都没抢到 :(~~

**Comment by squareRoot3** [comment]
啊这 (,,´•ω•)ノ"(´っω•｀。) 可能是程序挂少了, 我 4 台电脑买台挂两个抢不同票种
