### ISSUE TITLE
一直显示验证已超时，打开滑块验证也没有用处。

### ISSUE THREAD

**Issue by bilibiliSilentH** [Just-Prog/Bilibili_show_ticket_auto_order#4]

**Comment by bilibiliSilentH** [comment]
![image](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order/assets/167333048/bfc4c86d-0a55-4afd-ac34-2e11cb43ecf8)
如图。

**Comment by Just-Prog** [comment]
有提示要求输入 `validate` 这一步吗

**Comment by Just-Prog** [comment]
建议更新为本仓库的 release ，原仓库版本无法处理验证码
